CREATE TABLE accidents (
	id int null,
AccidentNumber varchar null,
DateandTime  timestamp null,
NumberofMotorVehicles  float null,
NumberofInjuries float null,
NumberofFatalities int null,
PropertyDamage  varchar null,
HitandRun   varchar null,
ReportingOfficer  varchar null,
CollisionTypeCode float null,
CollisionTypeDescription varchar null,
WeatherCode  float null,
WeatherDescription varchar null,
IlluminationCode  float null,
IlluminationDescription  varchar null,
HarmfulCode varchar null,
HarmfulDescription  varchar null,
StreetAddress  varchar null,
City  varchar null,
State  varchar null,
ZIP float null,
RPA float null,
Precinct varchar null,
Latitude float null,
Longitude float null,
MappedLocation varchar null
)
