CREATE TABLE weather (
	id int null,
	dt int null,
	dt_iso  timestamp null,
	timezone int null,
	city_name varchar null,
	lat float null,
	lon float null,
	temp float null,
	feels_like  float null,
	temp_min  float null,
	temp_max  float null,
	pressure  int null,
	sea_level  float null,
	grnd_level float null,
	humidity  int null,
	wind_speed  float null,
	wind_deg  int null,
	rain_1h  float null,
	rain_3h  float null,
	snow_1h  float null,
	snow_3h  float null,
	clouds_all int null,
	weather_id  int null,
	weather_main  varchar null,
	weather_description  varchar null,
	weather_icon  varchar null
)
